language: bash
sudo: false
cache: apt

services:
  - docker

before_install:
  - docker pull unscramble/picolisp-unit
  - docker build --no-cache --rm -t unscramble/picolisp-unit .

install:
  - docker run unscramble/picolisp-unit /bin/sh -c "cd /tmp/picolisp-unit; make check"
