language: bash
sudo: false
cache: apt

services:
  - docker

before_install:
  - docker build --pull --cache-from unscramble/picolisp-unit -t unscramble/picolisp-unit .

install:
  - docker run unscramble/picolisp-unit /bin/sh -c "cd /tmp/picolisp-unit; make check"
