language: bash
sudo: false
cache: apt

services:
  - docker

before_install:
  - docker pull jidoteki/picolisp-unit

install:
  - docker run jidoteki/picolisp-unit /bin/sh -c "cd /tmp/picolisp-unit; make check"
