language: bash
sudo: false
cache: apt

services:
  - docker

before_install:
  - docker build -t aw/picolisp-unit .

install:
  - docker run aw/picolisp-unit /bin/sh -c "cd /tmp/picolisp-unit; make check"
