language: bash
sudo: false
cache: apt

services:
  - docker

before_install:
  - docker pull unscramble/picolisp-unit
  - docker build --cache-from unscramble/picolisp-unit .

install:
  - docker run -v ${TRAVIS_BUILD_DIR}:/tmp/picolisp-unit unscramble/picolisp-unit /bin/sh -c "cd /tmp/picolisp-unit; make check"
